# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: bionic
cache: packages
apt_packages:
  - libudunits2-dev
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo apt-get -y install libgdal-dev
